version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${BD_USER}
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${BD_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

